export const routes = {
    ORDER: "/orders/:id",
    ORDER_FINISH: "/orders/finish",
    BOOK_HOUSE: "/filter",
    ADD_HOUSE: "/edit/add_house",
    ADD_HOUSE_CATEGORY: "/edit/add_house_category",
    EDIT_SERVICE: "/edit/service",
    EDIT_PRICE: "/edit/price",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_ORDER_SUMMARY: "/admin/order_summary",
    ADMIN_SERVICE_SHOP: "/admin/service_shop",
    PAYMENT: "/payment",
    ABOUT: "/about",
    SERVICES: "/services",
    CONTACTS: "/contacts",
};