"""clients and client_categories tables

Revision ID: 15ccde9210f8
Revises: 
Create Date: 2018-04-02 23:58:21.718352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ccde9210f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_category',
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_category_id')
    )
    op.create_index(op.f('ix_client_category_name'), 'client_category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_category_name'), table_name='client_category')
    op.drop_table('client_category')
    # ### end Alembic commands ###
