"""init

Revision ID: 513d3f6a37e4
Revises: 
Create Date: 2018-04-08 19:37:25.810264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513d3f6a37e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_category',
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_category_id')
    )
    op.create_index(op.f('ix_client_category_name'), 'client_category', ['name'], unique=True)
    op.create_table('house_object',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('order_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_method',
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_status',
    sa.Column('payment_status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('payment_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recreation_center',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('center_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_category_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_category.client_category_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_first_name'), 'client', ['first_name'], unique=False)
    op.create_index(op.f('ix_client_last_name'), 'client', ['last_name'], unique=False)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=False)
    op.create_table('house_category',
    sa.Column('house_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['recreation_center.center_id'], ),
    sa.PrimaryKeyConstraint('house_category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_status_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.payment_method_id'], ),
    sa.ForeignKeyConstraint(['payment_status_id'], ['payment_status.payment_status_id'], ),
    sa.PrimaryKeyConstraint('payment_id', 'payment_status_id', 'payment_method_id', 'payment_time')
    )
    op.create_table('cashless_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('house_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_category_id'], ['house_category.house_category_id'], ),
    sa.PrimaryKeyConstraint('house_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('house_category_object',
    sa.Column('house_category_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_category_id'], ['house_category.house_category_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['house_object.object_id'], )
    )
    op.create_table('service_price',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('house_category_id', sa.Integer(), nullable=False),
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('price_start_time', sa.DateTime(), nullable=False),
    sa.Column('price_end_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_category.client_category_id'], ),
    sa.ForeignKeyConstraint(['house_category_id'], ['house_category.house_category_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'house_category_id', 'client_category_id', 'price_start_time', 'price_end_time')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.status_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_booking_time'), 'order', ['booking_time'], unique=False)
    op.create_index(op.f('ix_order_check_in_time'), 'order', ['check_in_time'], unique=False)
    op.create_index(op.f('ix_order_check_out_time'), 'order', ['check_out_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_check_out_time'), table_name='order')
    op.drop_index(op.f('ix_order_check_in_time'), table_name='order')
    op.drop_index(op.f('ix_order_booking_time'), table_name='order')
    op.drop_table('order')
    op.drop_table('service_price')
    op.drop_table('house_category_object')
    op.drop_table('house')
    op.drop_table('cashless_transaction')
    op.drop_table('payment')
    op.drop_table('house_category')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_last_name'), table_name='client')
    op.drop_index(op.f('ix_client_first_name'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    op.drop_table('service')
    op.drop_table('recreation_center')
    op.drop_table('payment_status')
    op.drop_table('payment_method')
    op.drop_table('order_status')
    op.drop_table('house_object')
    op.drop_index(op.f('ix_client_category_name'), table_name='client_category')
    op.drop_table('client_category')
    # ### end Alembic commands ###
