"""clients and client_categories tables

Revision ID: 628078296452
Revises: 15ccde9210f8
Create Date: 2018-04-03 00:10:29.451645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628078296452'
down_revision = '15ccde9210f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_category_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_category.client_category_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_first_name'), 'client', ['first_name'], unique=False)
    op.create_index(op.f('ix_client_last_name'), 'client', ['last_name'], unique=False)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_last_name'), table_name='client')
    op.drop_index(op.f('ix_client_first_name'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
