"""add password_hash to client

Revision ID: 91ec39084731
Revises: 628078296452
Create Date: 2018-04-03 10:48:46.879225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ec39084731'
down_revision = '628078296452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.alter_column('client', 'client_category_id',
               existing_type=sa.VARCHAR(length=64))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_category_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('client', 'password_hash')
    # ### end Alembic commands ###
